import {
  Amphora,
  Barrel,
  BottleWine,
  Cylinder,
  Droplet,
  Earth,
  GlassWater,
  type LucideIcon,
  Milk,
  PaintBucket,
  Sailboat,
  Ship,
  Trees,
  Truck,
  Utensils,
  Waves,
  WavesLadder,
} from 'lucide-react'
import type { TierId } from '@/types'

/** UI icons per tier. Imported one by one so the bundle only carries these 17 glyphs. */
export const TIER_ICONS: Readonly<Record<TierId, LucideIcon>> = {
  drop: Droplet,
  tablespoon: Utensils,
  cup: GlassWater,
  'small-bottle': Milk,
  bottle: BottleWine,
  bucket: PaintBucket,
  jug: Amphora,
  drum: Barrel,
  'small-tank': Cylinder,
  tank: Cylinder,
  'small-truck': Truck,
  'large-truck': Truck,
  'residential-pool': WavesLadder,
  'large-pool': WavesLadder,
  'olympic-pool': WavesLadder,
  'small-lake': Trees,
  amazon: Waves,
  mediterranean: Sailboat,
  atlantic: Ship,
  earth: Earth,
}
